name: Lint and Test on PRs

on:
  pull_request:
    branches: [ main, develop ]

env:
  ECR_REPOSITORY: naturescot/trap-registration-return
  TRR_PORT: 3010
  TRR_SESSION_SECRET: override_this_value
  TR_API_URL: override_this_value

jobs:

  lint_and_test:
    name: Lint and Test the Project
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Install all the pre-requisites
      run: npm ci

    - name: Check the linter
      run: npm run lint

    - name: Check the pre-start operations
      run: npm run prestart

    - name: Check the integration tests
      run: npm run test
